import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import SearchComp from "@/components/SearchComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="bg-cover bg-no-repeat text-white px-2"
          style={{
            backgroundImage: `url('https://www.awxcdn.com/adc-assets/images/hero/4/1920x450.jpg')`,
          }}
        >
          <Nav />
          <div className="max-w-6xl mx-auto min-h-[250px]">
            <SearchComp />
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
